### PR TITLE
Update README.md link to CMD options

### PR DESCRIPTION
**Pull request by fulldecent**
This change is [Reviewable](https://reviewable.io/reviews/niluje/fbink/51)

### CODE REVIEW

**Comment by NiLuJe** [comment]
Reading unprocessed printf tokens requires a weird kind of dedication, but, why not ;o).

**Comment by fulldecent** [comment]
That's right!

Separately, I would be happy to contribute a translation of the `printf` documentation into a command line readme in Markdown.

It didn't seem to fit in the main readme, but if you'd like it just tell me where to put it.

**Comment by NiLuJe** [comment]
To be honest, I originally purposefully did NOT do that because my experience with that approach in [KindleTool](https://github.com/NiLuJe/KindleTool) lead to pain & misery with having to maintain three slightly different copies of the same thing (printf, md, man) ^^.

That said, given that I've almost run our of free getopt token in FBInk anyways, it's unlikely to see any massive changes, so, sure, go ahead ;).

(Because, to be fair, KindleTool happens to require adding stupid device ids to the help listing every other day, which kinda compounds the annoyance factor ^^).

**Comment by NiLuJe** [comment]
As to where to put it, that's a good question. I'd say a CLI.md in the root folder, with a link to it in the README?

**Pull request merged**
