### PR TITLE
add support for bq cervantes and fnac touch devices

### PR DESCRIPTION
**Pull request by pazos**
add support for bq cervantes and fnac touchlight devices (a list of devices on https://blog.bq.com/es/bq-ereaders-developers-program/)

### CODE REVIEW

**Comment by NiLuJe** [comment]
That's a good start ;). With a bit of luck, there's no weird quirks to take into account, and it's basically all that's needed ;).

Speaking of: there's a bunch more of ifdeffery involved in fbink_internal.h for the mxcfb header selection, and un fbin_cmd.c for the help message ;).

**Comment by NiLuJe** [comment]
And, of course, a true no-op in fbink_init to silence that Kobo warning ;).

**Comment by pazos** [comment]
@NiLuJe thanks for the hints.

I've added device detection based on HWCONFIG pcb ids and added a deviceQuirks for new cervantes3/cervantes4 devices (based on KoboMk7 update). Everything works as expected on my end :smile: 

TODO: don't build button_scan when targetting cervantes devices :P

**Comment by NiLuJe** [comment]
:+1: 

Yeah, currently, Mk7 Kobo devices also still handle the legacy ioctls ;).

**Comment by pazos** [comment]
It seems than button_scan binary is built even for kindle. So its out of the scope for this PR. Please feel free to review :+1:

**Comment by NiLuJe** [comment]
Yep, it just returns ENOSYS on unsupported devices with yet another bit of iffdeffery ;).

Besides that, I kind of preferred the typedef in the header and not inside the body of the function ;).

That's the only thing that really jumped out after a quick look see, I'll take another look tomorrow, thanks!

**Comment by NiLuJe** [comment]
Merging, thanks!

(FYI: We don't get notifications on a force push, so don't hesitate to ping when you do that ;)).

**Pull request merged**
